package rust

import (
	"os"
	"path/filepath"
	"testing"
)

// ---------------------------------------------------------------------------
// Lockfile parser tests
// ---------------------------------------------------------------------------

func TestLoadCargoLock(t *testing.T) {
	dir := t.TempDir()

	// Write a minimal Cargo.toml so we know the root name.
	cargoToml := `[package]
name = "myapp"
version = "0.1.0"

[dependencies]
serde = "1.0"
reqwest = "0.11"
`
	if err := os.WriteFile(filepath.Join(dir, "Cargo.toml"), []byte(cargoToml), 0o600); err != nil {
		t.Fatal(err)
	}

	lockContent := `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "myapp"
version = "0.1.0"
dependencies = [
  "serde",
  "reqwest",
]

[[package]]
name = "serde"
version = "1.0.193"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "reqwest"
version = "0.11.23"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
  "serde",
]
`
	if err := os.WriteFile(filepath.Join(dir, "Cargo.lock"), []byte(lockContent), 0o600); err != nil {
		t.Fatal(err)
	}

	pkgs, err := loadCargoLock(dir)
	if err != nil {
		t.Fatalf("loadCargoLock: %v", err)
	}

	byName := make(map[string]RustPackage)
	for _, p := range pkgs {
		byName[p.Name] = p
	}

	if _, ok := byName["serde"]; !ok {
		t.Error("expected 'serde' in packages")
	}
	if byName["serde"].Version != "1.0.193" {
		t.Errorf("serde version: got %q, want %q", byName["serde"].Version, "1.0.193")
	}
	if _, ok := byName["reqwest"]; !ok {
		t.Error("expected 'reqwest' in packages")
	}
	if byName["reqwest"].Version != "0.11.23" {
		t.Errorf("reqwest version: got %q, want %q", byName["reqwest"].Version, "0.11.23")
	}
	// Root package should be filtered out.
	if _, ok := byName["myapp"]; ok {
		t.Error("root package 'myapp' should be filtered out")
	}
	// reqwest should depend on serde.
	found := false
	for _, dep := range byName["reqwest"].Dependencies {
		if dep == "serde" {
			found = true
		}
	}
	if !found {
		t.Error("reqwest should depend on serde")
	}
}

func TestLoadCargoToml(t *testing.T) {
	dir := t.TempDir()
	content := `[package]
name = "myapp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
reqwest = { version = "0.11", features = ["json"] }

[dev-dependencies]
tokio-test = "0.4"
`
	if err := os.WriteFile(filepath.Join(dir, "Cargo.toml"), []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}

	pkgs, err := loadCargoToml(dir)
	if err != nil {
		t.Fatalf("loadCargoToml: %v", err)
	}

	byName := make(map[string]RustPackage)
	for _, p := range pkgs {
		byName[p.Name] = p
	}

	if _, ok := byName["serde"]; !ok {
		t.Error("expected 'serde' in packages")
	}
	if byName["serde"].Version != "1.0" {
		t.Errorf("serde version: got %q, want %q", byName["serde"].Version, "1.0")
	}
	if _, ok := byName["reqwest"]; !ok {
		t.Error("expected 'reqwest' in packages")
	}
	if _, ok := byName["tokio-test"]; !ok {
		t.Error("expected 'tokio-test' (dev-dep) in packages")
	}
}

// ---------------------------------------------------------------------------
// Capability detection tests
// ---------------------------------------------------------------------------

func TestDetectCapabilities(t *testing.T) {
	dir := t.TempDir()
	src := `use std::process::Command;
use std::fs;
use reqwest;

fn main() {
    let output = Command::new("ls").output().unwrap();
    let key = std::env::var("SECRET_KEY").unwrap();
    let data = std::fs::read("file.txt").unwrap();
    unsafe {
        // raw pointer operations
    }
}
`
	if err := os.WriteFile(filepath.Join(dir, "main.rs"), []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}

	caps := Detect(dir)

	wantCaps := []string{"exec", "env", "fs:read", "fs:write", "network", "unsafe"}
	for _, want := range wantCaps {
		if !caps.Has(want) {
			t.Errorf("expected capability %q to be detected", want)
		}
	}
}

func TestDetectNoCapabilities(t *testing.T) {
	dir := t.TempDir()
	src := `fn add(a: i32, b: i32) -> i32 {
    a + b
}

fn greet(name: &str) -> String {
    format!("Hello, {}!", name)
}
`
	if err := os.WriteFile(filepath.Join(dir, "lib.rs"), []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}

	caps := Detect(dir)
	if !caps.IsEmpty() {
		t.Errorf("expected no capabilities for benign code, got: %v", caps.List())
	}
}

// ---------------------------------------------------------------------------
// Adapter integration test
// ---------------------------------------------------------------------------

func TestAdapterLoad(t *testing.T) {
	dir := t.TempDir()
	content := `[package]
name = "myapp"
version = "0.1.0"

[dependencies]
serde = "1.0"
reqwest = "0.11"
`
	if err := os.WriteFile(filepath.Join(dir, "Cargo.toml"), []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}

	a := &Adapter{}
	if a.Name() != "rust" {
		t.Errorf("Name(): got %q, want %q", a.Name(), "rust")
	}

	g, err := a.Load(dir)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if g == nil {
		t.Fatal("Load returned nil graph")
	}

	// Should have root module + at least the two deps.
	if len(g.Modules) < 2 {
		t.Errorf("expected at least 2 modules, got %d", len(g.Modules))
	}

	if _, ok := g.Packages["serde"]; !ok {
		t.Error("expected 'serde' package in graph")
	}
	if _, ok := g.Packages["reqwest"]; !ok {
		t.Error("expected 'reqwest' package in graph")
	}
}

// ---------------------------------------------------------------------------
// Fuzz test
// ---------------------------------------------------------------------------

func FuzzParseCargoLock(f *testing.F) {
	f.Add([]byte("[[package]]\nname = \"serde\"\nversion = \"1.0.193\"\n"))
	f.Add([]byte(""))
	f.Add([]byte("# comment only"))
	f.Add([]byte("version = 3\n[[package]]\nname = \"foo\"\nversion = \"0.1.0\"\ndependencies = [\"bar\"]\n"))

	f.Fuzz(func(t *testing.T, data []byte) {
		defer func() { recover() }() //nolint:errcheck

		dir := t.TempDir()
		if err := os.WriteFile(filepath.Join(dir, "Cargo.lock"), data, 0o600); err != nil {
			return
		}
		loadCargoLock(dir) //nolint:errcheck
	})
}
