package node

import "github.com/1homsi/gorisk/internal/capability"

// importPatterns maps npm package / Node built-in module names to capabilities.
var importPatterns = map[string][]capability.Capability{
	"fs":                  {capability.CapFSRead, capability.CapFSWrite},
	"node:fs":             {capability.CapFSRead, capability.CapFSWrite},
	"fs/promises":         {capability.CapFSRead, capability.CapFSWrite},
	"node:fs/promises":    {capability.CapFSRead, capability.CapFSWrite},
	"path":                {capability.CapFSRead},
	"node:path":           {capability.CapFSRead},
	"os":                  {capability.CapEnv},
	"node:os":             {capability.CapEnv},
	"child_process":       {capability.CapExec},
	"node:child_process":  {capability.CapExec},
	"net":                 {capability.CapNetwork},
	"node:net":            {capability.CapNetwork},
	"http":                {capability.CapNetwork},
	"node:http":           {capability.CapNetwork},
	"https":               {capability.CapNetwork},
	"node:https":          {capability.CapNetwork},
	"tls":                 {capability.CapNetwork, capability.CapCrypto},
	"node:tls":            {capability.CapNetwork, capability.CapCrypto},
	"crypto":              {capability.CapCrypto},
	"node:crypto":         {capability.CapCrypto},
	"vm":                  {capability.CapUnsafe},
	"node:vm":             {capability.CapUnsafe},
	"module":              {capability.CapPlugin},
	"node:module":         {capability.CapPlugin},
	"worker_threads":      {capability.CapExec},
	"node:worker_threads": {capability.CapExec},
	"dgram":               {capability.CapNetwork},
	"node:dgram":          {capability.CapNetwork},
	"readline":            {capability.CapFSRead},
	"node:readline":       {capability.CapFSRead},
	"process":             {capability.CapEnv},
	"node:process":        {capability.CapEnv},
	"cluster":             {capability.CapExec},
	"node:cluster":        {capability.CapExec},
}

// callPatterns maps function call substrings to capabilities.
var callPatterns = map[string][]capability.Capability{
	"eval(":                {capability.CapUnsafe},
	"new Function(":        {capability.CapUnsafe},
	"exec(":                {capability.CapExec},
	"execSync(":            {capability.CapExec},
	"execFile(":            {capability.CapExec},
	"execFileSync(":        {capability.CapExec},
	"spawn(":               {capability.CapExec},
	"spawnSync(":           {capability.CapExec},
	"fork(":                {capability.CapExec},
	"fetch(":               {capability.CapNetwork},
	"axios.":               {capability.CapNetwork},
	"request(":             {capability.CapNetwork},
	"got(":                 {capability.CapNetwork},
	"readFile":             {capability.CapFSRead},
	"readFileSync":         {capability.CapFSRead},
	"readdir":              {capability.CapFSRead},
	"readdirSync":          {capability.CapFSRead},
	"writeFile":            {capability.CapFSWrite},
	"writeFileSync":        {capability.CapFSWrite},
	"appendFile":           {capability.CapFSWrite},
	"appendFileSync":       {capability.CapFSWrite},
	"unlink(":              {capability.CapFSWrite},
	"unlinkSync(":          {capability.CapFSWrite},
	"rmdir(":               {capability.CapFSWrite},
	"rmdirSync(":           {capability.CapFSWrite},
	"mkdir(":               {capability.CapFSWrite},
	"mkdirSync(":           {capability.CapFSWrite},
	"process.env":          {capability.CapEnv},
	"require('vm')":        {capability.CapUnsafe},
	"createRequire(":       {capability.CapPlugin},
	"vm.runInNewContext(":  {capability.CapUnsafe},
	"vm.runInThisContext(": {capability.CapUnsafe},
}
