package python

import (
	"os"
	"path/filepath"
	"testing"
)

// ---------------------------------------------------------------------------
// Lockfile parser tests
// ---------------------------------------------------------------------------

func TestLoadRequirementsTxt(t *testing.T) {
	dir := t.TempDir()
	content := `# project dependencies
requests==2.31.0
flask>=2.0
# dev tool
pytest
-r other-requirements.txt
`
	if err := os.WriteFile(filepath.Join(dir, "requirements.txt"), []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}

	pkgs, err := loadRequirementsTxt(dir)
	if err != nil {
		t.Fatalf("loadRequirementsTxt: %v", err)
	}

	byName := make(map[string]PythonPackage)
	for _, p := range pkgs {
		byName[p.Name] = p
	}

	if _, ok := byName["requests"]; !ok {
		t.Error("expected 'requests' in packages")
	}
	if byName["requests"].Version != "2.31.0" {
		t.Errorf("requests version: got %q, want %q", byName["requests"].Version, "2.31.0")
	}
	if _, ok := byName["flask"]; !ok {
		t.Error("expected 'flask' in packages")
	}
	if _, ok := byName["pytest"]; !ok {
		t.Error("expected 'pytest' in packages")
	}
	// The -r option should not be parsed as a package.
	if _, ok := byName["-r"]; ok {
		t.Error("option line '-r' should not be a package")
	}
}

func TestLoadPoetryLock(t *testing.T) {
	dir := t.TempDir()
	lockContent := `# This file is automatically @generated by Poetry.
# It is not intended for manual editing.

[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.7"

[package.dependencies]
charset-normalizer = ">=2,<4"
idna = ">=2.5,<4"
urllib3 = ">=1.21.1,<3"
certifi = ">=2017.4.22"

[[package]]
name = "urllib3"
version = "2.0.4"
description = "HTTP library with thread-safe connection pooling."
optional = false
python-versions = ">=3.7"
`
	pyproject := `[tool.poetry]
name = "my-project"
version = "0.1.0"

[tool.poetry.dependencies]
python = ">=3.9"
requests = "^2.31.0"
`
	if err := os.WriteFile(filepath.Join(dir, "poetry.lock"), []byte(lockContent), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "pyproject.toml"), []byte(pyproject), 0o600); err != nil {
		t.Fatal(err)
	}

	pkgs, err := loadPoetryLock(dir)
	if err != nil {
		t.Fatalf("loadPoetryLock: %v", err)
	}

	byName := make(map[string]PythonPackage)
	for _, p := range pkgs {
		byName[p.Name] = p
	}

	if _, ok := byName["requests"]; !ok {
		t.Error("expected 'requests'")
	}
	if byName["requests"].Version != "2.31.0" {
		t.Errorf("requests version: got %q", byName["requests"].Version)
	}
	if !byName["requests"].Direct {
		t.Error("requests should be a direct dep")
	}
	// urllib3 is a transitive dep.
	if byName["urllib3"].Direct {
		t.Error("urllib3 should not be a direct dep")
	}
	// requests should have urllib3 as a dependency.
	found := false
	for _, dep := range byName["requests"].Dependencies {
		if dep == "urllib3" {
			found = true
		}
	}
	if !found {
		t.Error("requests should depend on urllib3")
	}
}

func TestLoadPipfileLock(t *testing.T) {
	dir := t.TempDir()
	lockContent := `{
    "_meta": {
        "hash": {"sha256": "abc"},
        "pipfile-spec": 6,
        "requires": {"python_version": "3.11"},
        "sources": [{"name": "pypi", "url": "https://pypi.org/simple", "verify_ssl": true}]
    },
    "default": {
        "flask": {"version": "==3.0.0", "hashes": ["sha256:abc"]},
        "werkzeug": {"version": "==3.0.1", "hashes": ["sha256:def"]}
    },
    "develop": {
        "pytest": {"version": "==7.4.0", "hashes": ["sha256:ghi"]}
    }
}`
	pipfile := `[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "*"

[dev-packages]
pytest = "*"
`
	if err := os.WriteFile(filepath.Join(dir, "Pipfile.lock"), []byte(lockContent), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "Pipfile"), []byte(pipfile), 0o600); err != nil {
		t.Fatal(err)
	}

	pkgs, err := loadPipfileLock(dir)
	if err != nil {
		t.Fatalf("loadPipfileLock: %v", err)
	}

	byName := make(map[string]PythonPackage)
	for _, p := range pkgs {
		byName[p.Name] = p
	}

	if _, ok := byName["flask"]; !ok {
		t.Error("expected 'flask'")
	}
	if byName["flask"].Version != "3.0.0" {
		t.Errorf("flask version: got %q, want %q", byName["flask"].Version, "3.0.0")
	}
	if !byName["flask"].Direct {
		t.Error("flask should be a direct dep")
	}
}

// ---------------------------------------------------------------------------
// Capability detection tests
// ---------------------------------------------------------------------------

func TestDetectCapabilities(t *testing.T) {
	dir := t.TempDir()
	src := `import subprocess
import os
import requests

def run_cmd(cmd):
    subprocess.run(cmd, shell=True)

def fetch(url):
    return requests.get(url)

def read_env():
    return os.getenv("SECRET_KEY")
`
	if err := os.WriteFile(filepath.Join(dir, "main.py"), []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}

	caps := Detect(dir)

	wantCaps := []string{"exec", "network", "env"}
	for _, want := range wantCaps {
		if !caps.Has(want) {
			t.Errorf("expected capability %q to be detected", want)
		}
	}
}

func TestDetectNoCapabilities(t *testing.T) {
	dir := t.TempDir()
	src := `def add(a, b):
    return a + b

def greet(name):
    return f"Hello, {name}"
`
	if err := os.WriteFile(filepath.Join(dir, "utils.py"), []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}

	caps := Detect(dir)
	if !caps.IsEmpty() {
		t.Errorf("expected no capabilities for benign code, got: %v", caps.List())
	}
}

// ---------------------------------------------------------------------------
// Adapter integration test
// ---------------------------------------------------------------------------

func TestAdapterLoad(t *testing.T) {
	dir := t.TempDir()
	requirements := `requests==2.31.0
flask==3.0.0
`
	if err := os.WriteFile(filepath.Join(dir, "requirements.txt"), []byte(requirements), 0o600); err != nil {
		t.Fatal(err)
	}

	a := &Adapter{}
	if a.Name() != "python" {
		t.Errorf("Name(): got %q, want %q", a.Name(), "python")
	}

	g, err := a.Load(dir)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if g == nil {
		t.Fatal("Load returned nil graph")
	}

	// Should have root module + at least the two deps.
	if len(g.Modules) < 2 {
		t.Errorf("expected at least 2 modules, got %d", len(g.Modules))
	}

	if _, ok := g.Packages["requests"]; !ok {
		t.Error("expected 'requests' package in graph")
	}
	if _, ok := g.Packages["flask"]; !ok {
		t.Error("expected 'flask' package in graph")
	}
}

// ---------------------------------------------------------------------------
// Fuzz test
// ---------------------------------------------------------------------------

func FuzzParseRequirementsTxt(f *testing.F) {
	f.Add([]byte("requests==2.31.0\nflask>=2.0\n"))
	f.Add([]byte(""))
	f.Add([]byte("# comment only"))
	f.Add([]byte("-r other.txt\n--index-url https://example.com\n"))

	f.Fuzz(func(t *testing.T, data []byte) {
		defer func() { recover() }() //nolint:errcheck

		dir := t.TempDir()
		if err := os.WriteFile(filepath.Join(dir, "requirements.txt"), data, 0o600); err != nil {
			return
		}
		loadRequirementsTxt(dir) //nolint:errcheck
	})
}

// ---------------------------------------------------------------------------
// Malformed / empty input tests — verify no panic and graceful handling
// ---------------------------------------------------------------------------

func TestLoadRequirementsTxtEmpty(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "requirements.txt"), []byte{}, 0o600); err != nil {
		t.Fatal(err)
	}
	pkgs, err := loadRequirementsTxt(dir)
	if err != nil {
		t.Fatalf("loadRequirementsTxt() unexpected error for empty file: %v", err)
	}
	if len(pkgs) != 0 {
		t.Errorf("expected 0 packages for empty requirements.txt, got %d", len(pkgs))
	}
}

func TestLoadRequirementsTxtMalformed(t *testing.T) {
	// requirements.txt with only invalid/option lines — should return empty, not error.
	dir := t.TempDir()
	content := `# comment
-r other.txt
--extra-index-url https://example.com
   
`
	if err := os.WriteFile(filepath.Join(dir, "requirements.txt"), []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	pkgs, err := loadRequirementsTxt(dir)
	if err != nil {
		t.Fatalf("loadRequirementsTxt() unexpected error: %v", err)
	}
	if len(pkgs) != 0 {
		t.Errorf("expected 0 packages for all-options file, got %d", len(pkgs))
	}
}

func TestLoadPoetryLockEmpty(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "poetry.lock"), []byte{}, 0o600); err != nil {
		t.Fatal(err)
	}
	pkgs, err := loadPoetryLock(dir)
	if err != nil {
		t.Fatalf("loadPoetryLock() unexpected error for empty file: %v", err)
	}
	if len(pkgs) != 0 {
		t.Errorf("expected 0 packages for empty poetry.lock, got %d", len(pkgs))
	}
}

func TestLoadPoetryLockMalformed(t *testing.T) {
	// poetry.lock with no [[package]] sections — should return empty, not error.
	dir := t.TempDir()
	content := `# This file is automatically @generated by Poetry.
[metadata]
lock-version = "2.0"
`
	if err := os.WriteFile(filepath.Join(dir, "poetry.lock"), []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	pkgs, err := loadPoetryLock(dir)
	if err != nil {
		t.Fatalf("loadPoetryLock() unexpected error: %v", err)
	}
	if len(pkgs) != 0 {
		t.Errorf("expected 0 packages for metadata-only poetry.lock, got %d", len(pkgs))
	}
}

func TestLoadPipfileLockEmpty(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "Pipfile.lock"), []byte{}, 0o600); err != nil {
		t.Fatal(err)
	}
	pkgs, err := loadPipfileLock(dir)
	if err != nil {
		t.Fatalf("loadPipfileLock() unexpected error for empty file: %v", err)
	}
	if len(pkgs) != 0 {
		t.Errorf("expected 0 packages for empty Pipfile.lock, got %d", len(pkgs))
	}
}

func TestLoadPipfileLockMalformed(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "Pipfile.lock"), []byte(`{not valid json`), 0o600); err != nil {
		t.Fatal(err)
	}
	_, err := loadPipfileLock(dir)
	if err == nil {
		t.Error("expected error for malformed Pipfile.lock, got nil")
	}
}

func TestLoadPyprojectTOMLEmpty(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "pyproject.toml"), []byte{}, 0o600); err != nil {
		t.Fatal(err)
	}
	pkgs, err := loadPyprojectTOML(dir)
	if err != nil {
		t.Fatalf("loadPyprojectTOML() unexpected error for empty file: %v", err)
	}
	if len(pkgs) != 0 {
		t.Errorf("expected 0 packages for empty pyproject.toml, got %d", len(pkgs))
	}
}

func TestLoadPyprojectTOMLMalformed(t *testing.T) {
	// pyproject.toml with no [project] section — should return empty, not error.
	dir := t.TempDir()
	content := `[tool.black]
line-length = 88
`
	if err := os.WriteFile(filepath.Join(dir, "pyproject.toml"), []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	pkgs, err := loadPyprojectTOML(dir)
	if err != nil {
		t.Fatalf("loadPyprojectTOML() unexpected error: %v", err)
	}
	if len(pkgs) != 0 {
		t.Errorf("expected 0 packages for non-project pyproject.toml, got %d", len(pkgs))
	}
}

func TestLoadEmptyDir(t *testing.T) {
	dir := t.TempDir()
	_, err := Load(dir)
	if err == nil {
		t.Error("expected error for directory with no Python lockfiles")
	}
}
