package pr

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/1homsi/gorisk/internal/capability"
	"github.com/1homsi/gorisk/internal/prdiff"
)

func TestRun(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping git test in short mode")
	}

	testDir := t.TempDir()

	// Initialize git repo
	initCmd := exec.Command("git", "init")
	initCmd.Dir = testDir
	if err := initCmd.Run(); err != nil {
		t.Skip("git not available")
	}

	configEmail := exec.Command("git", "config", "user.email", "test@example.com")
	configEmail.Dir = testDir
	if err := configEmail.Run(); err != nil {
		t.Skip("git config failed")
	}

	configName := exec.Command("git", "config", "user.name", "Test User")
	configName.Dir = testDir
	if err := configName.Run(); err != nil {
		t.Skip("git config failed")
	}

	testCode := `package main

import "crypto/sha256"

func main() {
	sha256.New()
}
`
	if err := os.WriteFile(filepath.Join(testDir, "main.go"), []byte(testCode), 0600); err != nil {
		t.Fatal(err)
	}

	goMod := `module test
go 1.22
`
	if err := os.WriteFile(filepath.Join(testDir, "go.mod"), []byte(goMod), 0600); err != nil {
		t.Fatal(err)
	}

	addCmd := exec.Command("git", "add", ".")
	addCmd.Dir = testDir
	if err := addCmd.Run(); err != nil {
		t.Skip("git add failed")
	}

	commitCmd := exec.Command("git", "commit", "-m", "initial")
	commitCmd.Dir = testDir
	if err := commitCmd.Run(); err != nil {
		t.Skip("git commit failed")
	}

	origDir, _ := os.Getwd()
	defer os.Chdir(origDir)
	os.Chdir(testDir)

	// pr command needs git commits and typically fails in test environment
	// Just verify it runs without crashing
	exitCode := Run([]string{})
	_ = exitCode
}

func TestRunWithJSON(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping git test in short mode")
	}

	testDir := t.TempDir()
	testCode := `package main

func main() {}
`
	if err := os.WriteFile(filepath.Join(testDir, "main.go"), []byte(testCode), 0600); err != nil {
		t.Fatal(err)
	}

	goMod := `module test
go 1.22
`
	if err := os.WriteFile(filepath.Join(testDir, "go.mod"), []byte(goMod), 0600); err != nil {
		t.Fatal(err)
	}

	origDir, _ := os.Getwd()
	defer os.Chdir(origDir)
	os.Chdir(testDir)

	exitCode := Run([]string{"--json"})
	_ = exitCode
}

func TestRunWithComment_NoToken(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping git test in short mode")
	}

	testDir := t.TempDir()
	testCode := `package main

func main() {}
`
	if err := os.WriteFile(filepath.Join(testDir, "main.go"), []byte(testCode), 0600); err != nil {
		t.Fatal(err)
	}
	goMod := `module test
go 1.22
`
	if err := os.WriteFile(filepath.Join(testDir, "go.mod"), []byte(goMod), 0600); err != nil {
		t.Fatal(err)
	}

	origDir, _ := os.Getwd()
	defer os.Chdir(origDir)
	os.Chdir(testDir)

	// Without GITHUB_TOKEN set, --comment should warn and skip silently
	os.Unsetenv("GITHUB_TOKEN")
	exitCode := Run([]string{"--comment"})
	// May fail due to git diff issues in test env, but should not panic
	_ = exitCode
}

func TestBuildCommentBody_Added(t *testing.T) {
	var caps capability.CapabilitySet
	caps.Add(capability.CapExec)
	caps.Add(capability.CapNetwork)

	report := prdiff.PRDiffReport{
		Added: []prdiff.ModuleDiff{
			{Module: "foo/bar", NewVersion: "v1.2.3", Caps: caps},
		},
	}

	body := buildCommentBody(report)

	if !strings.Contains(body, "## gorisk scan diff") {
		t.Error("body should contain heading")
	}
	if !strings.Contains(body, "foo/bar") {
		t.Error("body should contain module name")
	}
	if !strings.Contains(body, "| Package | Before | After | New Caps |") {
		t.Error("body should contain table header")
	}
	if !strings.Contains(body, "> Generated by gorisk pr") {
		t.Error("body should contain footer")
	}
}

func TestBuildCommentBody_Updated(t *testing.T) {
	var caps capability.CapabilitySet
	caps.Add(capability.CapExec)

	report := prdiff.PRDiffReport{
		Updated: []prdiff.ModuleDiff{
			{Module: "baz/qux", OldVersion: "v1.0.0", NewVersion: "v2.0.0", Caps: caps, CapEscalated: true},
		},
	}

	body := buildCommentBody(report)

	if !strings.Contains(body, "baz/qux") {
		t.Error("body should contain module name")
	}
	if !strings.Contains(body, "v1.0.0") {
		t.Error("body should contain old version")
	}
	if !strings.Contains(body, "v2.0.0") {
		t.Error("body should contain new version")
	}
}

func TestBuildCommentBody_Removed(t *testing.T) {
	report := prdiff.PRDiffReport{
		Removed: []string{"old/dep"},
	}

	body := buildCommentBody(report)

	if !strings.Contains(body, "old/dep") {
		t.Error("body should contain removed module name")
	}
	if !strings.Contains(body, "removed") {
		t.Error("body should indicate removal")
	}
}
